#!/bin/bash

# 1) Create a container named `bagel-engine` with required resources

docker container create \
    --name bagel-engine \
    --mount type=tmpfs,destination=/scratch \
    --cpus 2 --memory 6Gb \
      quack-quack/bagel:latest

# 2) Copy the input script describing the calculation to the container

docker container cp  \
     h2o_svp_cas.json bagel-engine:/input.json

# 3) Perform the calculation, the container does the heavy lifting.
# The output generated by BAGEL is written to stdout.
docker container start \
     -a bagel-engine 

# 4) The CASSCF orbitals were written to the file '/orbitals.molden'.
# If we are interested in this file, we have to copy it back before
# deleting the container.
docker container cp \
     bagel-engine:/orbitals.molden  /tmp/orbitals.molden

# 5) Finally the container is destroyed and all resources are relased.
docker container rm bagel-engine
